[package]
version = "0.1.0"
name = "regex-matching"
edition = "2021"

[dependencies]
#alloy-sol-types = { workspace = true }
#alloy-r-types = { workspace = true }
sp1-zkvm = "3.0.0-rc4"
regex-lib = { path = "../lib" }
regex = "1.11.1"
bincode = "1.3.3"
sha2 = "0.10.8"
